// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/google/uuid"
)

// AuthWithGoogleInternalServerError is response for AuthWithGoogle operation.
type AuthWithGoogleInternalServerError struct{}

func (*AuthWithGoogleInternalServerError) authWithGoogleRes() {}

// AuthWithGoogleOK is response for AuthWithGoogle operation.
type AuthWithGoogleOK struct {
	SetCookie string
}

// GetSetCookie returns the value of SetCookie.
func (s *AuthWithGoogleOK) GetSetCookie() string {
	return s.SetCookie
}

// SetSetCookie sets the value of SetCookie.
func (s *AuthWithGoogleOK) SetSetCookie(val string) {
	s.SetCookie = val
}

func (*AuthWithGoogleOK) authWithGoogleRes() {}

type AuthWithGoogleReq struct {
	// Google JWT token.
	IdToken string `json:"idToken"`
}

// GetIdToken returns the value of IdToken.
func (s *AuthWithGoogleReq) GetIdToken() string {
	return s.IdToken
}

// SetIdToken sets the value of IdToken.
func (s *AuthWithGoogleReq) SetIdToken(val string) {
	s.IdToken = val
}

type BearerAuth struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *BearerAuth) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *BearerAuth) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *BearerAuth) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *BearerAuth) SetRoles(val []string) {
	s.Roles = val
}

// CreateTaskInternalServerError is response for CreateTask operation.
type CreateTaskInternalServerError struct{}

func (*CreateTaskInternalServerError) createTaskRes() {}

// Ref: #/components/schemas/CreateTaskRequest
type CreateTaskRequest struct {
	Title       string    `json:"title"`
	Description OptString `json:"description"`
}

// GetTitle returns the value of Title.
func (s *CreateTaskRequest) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *CreateTaskRequest) GetDescription() OptString {
	return s.Description
}

// SetTitle sets the value of Title.
func (s *CreateTaskRequest) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *CreateTaskRequest) SetDescription(val OptString) {
	s.Description = val
}

// DeleteTaskInternalServerError is response for DeleteTask operation.
type DeleteTaskInternalServerError struct{}

func (*DeleteTaskInternalServerError) deleteTaskRes() {}

// DeleteTaskNoContent is response for DeleteTask operation.
type DeleteTaskNoContent struct{}

func (*DeleteTaskNoContent) deleteTaskRes() {}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *ErrorResponse) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *ErrorResponse) SetMessage(val string) {
	s.Message = val
}

func (*ErrorResponse) createTaskRes() {}
func (*ErrorResponse) deleteTaskRes() {}

// ListTasksInternalServerError is response for ListTasks operation.
type ListTasksInternalServerError struct{}

func (*ListTasksInternalServerError) listTasksRes() {}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Task
type Task struct {
	ID          uuid.UUID    `json:"id"`
	Title       string       `json:"title"`
	Description OptNilString `json:"description"`
	Completed   bool         `json:"completed"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   time.Time    `json:"updatedAt"`
}

// GetID returns the value of ID.
func (s *Task) GetID() uuid.UUID {
	return s.ID
}

// GetTitle returns the value of Title.
func (s *Task) GetTitle() string {
	return s.Title
}

// GetDescription returns the value of Description.
func (s *Task) GetDescription() OptNilString {
	return s.Description
}

// GetCompleted returns the value of Completed.
func (s *Task) GetCompleted() bool {
	return s.Completed
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Task) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Task) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Task) SetID(val uuid.UUID) {
	s.ID = val
}

// SetTitle sets the value of Title.
func (s *Task) SetTitle(val string) {
	s.Title = val
}

// SetDescription sets the value of Description.
func (s *Task) SetDescription(val OptNilString) {
	s.Description = val
}

// SetCompleted sets the value of Completed.
func (s *Task) SetCompleted(val bool) {
	s.Completed = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Task) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Task) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

func (*Task) createTaskRes()       {}
func (*Task) updateTaskStatusRes() {}

// Ref: #/components/schemas/TaskListResponse
type TaskListResponse struct {
	Tasks []Task `json:"tasks"`
}

// GetTasks returns the value of Tasks.
func (s *TaskListResponse) GetTasks() []Task {
	return s.Tasks
}

// SetTasks sets the value of Tasks.
func (s *TaskListResponse) SetTasks(val []Task) {
	s.Tasks = val
}

func (*TaskListResponse) listTasksRes() {}

type Unauthorized struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Unauthorized) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Unauthorized) SetMessage(val string) {
	s.Message = val
}

func (*Unauthorized) authWithGoogleRes()   {}
func (*Unauthorized) createTaskRes()       {}
func (*Unauthorized) deleteTaskRes()       {}
func (*Unauthorized) listTasksRes()        {}
func (*Unauthorized) updateTaskStatusRes() {}

type UpdateTaskStatusBadRequest ErrorResponse

func (*UpdateTaskStatusBadRequest) updateTaskStatusRes() {}

// UpdateTaskStatusInternalServerError is response for UpdateTaskStatus operation.
type UpdateTaskStatusInternalServerError struct{}

func (*UpdateTaskStatusInternalServerError) updateTaskStatusRes() {}

type UpdateTaskStatusNotFound ErrorResponse

func (*UpdateTaskStatusNotFound) updateTaskStatusRes() {}

// Ref: #/components/schemas/UpdateTaskStatusRequest
type UpdateTaskStatusRequest struct {
	Completed bool `json:"completed"`
}

// GetCompleted returns the value of Completed.
func (s *UpdateTaskStatusRequest) GetCompleted() bool {
	return s.Completed
}

// SetCompleted sets the value of Completed.
func (s *UpdateTaskStatusRequest) SetCompleted(val bool) {
	s.Completed = val
}
