// Code generated by ogen, DO NOT EDIT.
package api

type AuthWithGoogleRes interface {
	authWithGoogleRes()
}

type CreateTaskRes interface {
	createTaskRes()
}

type DeleteTaskRes interface {
	deleteTaskRes()
}

type ListTasksRes interface {
	listTasksRes()
}

type UpdateTaskStatusRes interface {
	updateTaskStatusRes()
}
