// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthWithGoogleOperation   OperationName = "AuthWithGoogle"
	CreateTaskOperation       OperationName = "CreateTask"
	DeleteTaskOperation       OperationName = "DeleteTask"
	ListTasksOperation        OperationName = "ListTasks"
	UpdateTaskStatusOperation OperationName = "UpdateTaskStatus"
)
