// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AuthWithGoogle implements authWithGoogle operation.
//
// POST /auth/google
func (UnimplementedHandler) AuthWithGoogle(ctx context.Context, req *AuthWithGoogleReq) (r AuthWithGoogleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateTask implements createTask operation.
//
// POST /tasks
func (UnimplementedHandler) CreateTask(ctx context.Context, req *CreateTaskRequest) (r CreateTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTask implements deleteTask operation.
//
// DELETE /tasks/{taskId}
func (UnimplementedHandler) DeleteTask(ctx context.Context, params DeleteTaskParams) (r DeleteTaskRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTasks implements listTasks operation.
//
// GET /tasks
func (UnimplementedHandler) ListTasks(ctx context.Context) (r ListTasksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTaskStatus implements updateTaskStatus operation.
//
// PATCH /tasks/{taskId}/status
func (UnimplementedHandler) UpdateTaskStatus(ctx context.Context, req *UpdateTaskStatusRequest, params UpdateTaskStatusParams) (r UpdateTaskStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}
