// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AuthWithGoogle implements authWithGoogle operation.
	//
	// POST /auth/google
	AuthWithGoogle(ctx context.Context, req *AuthWithGoogleReq) (AuthWithGoogleRes, error)
	// CreateTask implements createTask operation.
	//
	// POST /tasks
	CreateTask(ctx context.Context, req *CreateTaskRequest) (CreateTaskRes, error)
	// DeleteTask implements deleteTask operation.
	//
	// DELETE /tasks/{taskId}
	DeleteTask(ctx context.Context, params DeleteTaskParams) (DeleteTaskRes, error)
	// ListTasks implements listTasks operation.
	//
	// GET /tasks
	ListTasks(ctx context.Context) (ListTasksRes, error)
	// UpdateTaskStatus implements updateTaskStatus operation.
	//
	// PATCH /tasks/{taskId}/status
	UpdateTaskStatus(ctx context.Context, req *UpdateTaskStatusRequest, params UpdateTaskStatusParams) (UpdateTaskStatusRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
