// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Task struct {
	ID          uuid.UUID
	UserID      int64
	Title       string
	Description sql.NullString
	IsCompleted bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID        int64
	GoogleSub string
	Name      sql.NullString
	IsActice  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
