// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0

package db

import (
	"database/sql"
	"time"
)

type Task struct {
	ID          int64
	UserID      interface{}
	Content     string
	IsCompleted bool
}

type User struct {
	ID        int64
	GoogleSub string
	Name      sql.NullString
	IsActice  bool
	CreatedAt time.Time
	UpdatedAt time.Time
}
