// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: tasks.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
insert into tasks (user_id, title, description)
values ($1, $2, $3)
returning id, user_id, title, description, is_completed, created_at, updated_at
`

type CreateTaskParams struct {
	UserID      int64
	Title       string
	Description sql.NullString
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask, arg.UserID, arg.Title, arg.Description)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :execrows
delete from tasks where id = $1 and user_id = $2
`

type DeleteTaskParams struct {
	ID     uuid.UUID
	UserID int64
}

func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteTask, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getTasks = `-- name: GetTasks :many
select id, user_id, title, description, is_completed, created_at, updated_at
from tasks
where user_id = $1
order by created_at desc
`

func (q *Queries) GetTasks(ctx context.Context, userID int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.IsCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByStatus = `-- name: GetTasksByStatus :many
select id, user_id, title, description, is_completed, created_at, updated_at
from tasks
where user_id = $1 and is_completed = $2
order by created_at desc
`

type GetTasksByStatusParams struct {
	UserID      int64
	IsCompleted bool
}

func (q *Queries) GetTasksByStatus(ctx context.Context, arg GetTasksByStatusParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByStatus, arg.UserID, arg.IsCompleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.IsCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
update tasks
set is_completed = $2, updated_at = now()
where id = $1 and user_id = $3
returning id, user_id, title, description, is_completed, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	ID          uuid.UUID
	IsCompleted bool
	UserID      int64
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatus, arg.ID, arg.IsCompleted, arg.UserID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
