// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: tasks.sql

package db

import (
	"context"
)

const createTask = `-- name: CreateTask :exec
insert into tasks(user_id, content) values($1, $2)
`

type CreateTaskParams struct {
	UserID  interface{}
	Content string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) error {
	_, err := q.db.ExecContext(ctx, createTask, arg.UserID, arg.Content)
	return err
}

const deleteTask = `-- name: DeleteTask :exec
delete from tasks where id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getTasks = `-- name: GetTasks :many
select id, user_id, content, is_completed from tasks where user_id = $1
`

func (q *Queries) GetTasks(ctx context.Context, userID interface{}) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.IsCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByStatus = `-- name: GetTasksByStatus :many
select id, user_id, content, is_completed from tasks where user_id = $1 and is_completed = $2
`

type GetTasksByStatusParams struct {
	UserID      interface{}
	IsCompleted bool
}

func (q *Queries) GetTasksByStatus(ctx context.Context, arg GetTasksByStatusParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksByStatus, arg.UserID, arg.IsCompleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.IsCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
update tasks set is_completed = $2 where id = $1
`

type UpdateTaskStatusParams struct {
	ID          int64
	IsCompleted bool
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.ID, arg.IsCompleted)
	return err
}
