// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.0
// source: users.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
select id, google_sub, name, is_actice, created_at, updated_at from users where id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GoogleSub,
		&i.Name,
		&i.IsActice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
